### ISSUE TITLE
Add support for data unmarshaling (e.g. via callback) to render errors nicely

### ISSUE THREAD

**Issue by julen** [iafan/agenda#2]
When agenda tests fail, the provided output falls short on providing helpful information:

https://github.com/iafan/agenda/blob/0f7177880c78fc92a5d7577f1ae2361f09d76ab3/agenda.go#L231-L233

i.e. only the file name of the snapshot that failed to match the test function's output is provided, but no clue about what failed to match and where.

Regenerating test files and checking the `git diff` output might work in isolated cases; in my experience though this is painful especially when iterating during development. This also means the expected output needs to be rewritten every time just to get a clue of what could be failing.

My expectation as a developer would be having human-readable output such as a colored diff as part of the failure report. The library could easily take this work out of developers' shoulders.

**Comment by iafan** [comment]
Agenda compares against raw bytes, since its goal is to be data-agnostic. Because of that, it doesn't know anything about data unmarshaling, and leaves that up to the higher-level tests that use Agenda. When Agenda-based test fails, the test wrapper can decide whether to render `output` and `referenceOutput` in a way that will help the user compare the differences.

**Comment by iafan** [comment]
I realized that what Agenda could do here is to provide some callback for unmarshaling. Right now it's not easy to do what I described above. So I'll reopen this issue and change its title accordingly.

**Comment by iafan** [comment]
What I'll do is an ability to provide an optional unmarshaling function (i.e. a function that renders `[]byte` into a `string`. If it's not provided, I can render the contents as a nicely-formatted HEX dump by default, suitable for diffing. After that, it should be straightforward to render a diff of the changes.
